### ISSUE TITLE
pnpm安装后 弹幕鼠标悬浮无反应 

### ISSUE THREAD

**Issue by NamISNaN** [dshuais/danmaku-vue#11]
### 问题
如题

请在此描述你的问题

### 代码实现
是否是代码版本问题？

在此附上你遇到问题的代码或代码截图。

```

```

### 环境

- danmaku-vue 版本: [e.g. v0.1.0]
- Vue 版本: [e.g. v2.0, v2.5, v2.6, v3.3]

**Comment by NamISNaN** [comment]
可以触发点击事件 但是无法触发hover事件
<img width="1037" alt="image" src="https://github.com/dshuais/danmaku-vue/assets/29939810/dcf27e50-35a6-4785-a7d2-6bbee3d7e9af">

**Comment by dshuais** [comment]
可以看一下`<Danmaku ...></Danmaku>`代码吗?

**Comment by NamISNaN** [comment]
<img width="680" alt="image" src="https://github.com/dshuais/danmaku-vue/assets/29939810/683f61b3-9614-43c4-af22-0333df56fa58">
感谢回复，Danmaku调用是从示例代码中直接copy的 ，自己额外写了.danmu-suspend 这个class 为background:red  但是也没有生效

**Comment by dshuais** [comment]
需要配置一下`isSuspend=true` 表示开启悬浮效果，因为为了防止创建多余的dom造成性能额外消耗，所以增加参数限制

**Comment by dshuais** [comment]
同时建议你更新一下`danmaku-vue@1.0.0` 到1.0.0版本

**Comment by NamISNaN** [comment]
好的，已经解决了，升级啦。 感谢～

**Comment by dshuais** [comment]
没事没事，另外`.danmu-suspend`设置背景不生效的话，需要设置`!important`强制一下，因为为了使`suspend`和`dm`使用同样的悬浮效果，所以在内部改变了`suspend`的背景的，还有疑问可看README或QA或继续提issue~

感谢使用~
