### ISSUE TITLE
对danmaku-vue项目的一些建议

### ISSUE THREAD

**Issue by hellodigua** [dshuais/danmaku-vue#14]
dshuais你好，我是vue-danmaku项目的原开发者，今天在npm上搜索我的项目时，搜出来一个代码和文档和vue-danmaku 90%相似的项目，看的我大为震撼。

简单看了下提交记录之后，我理解你可能有意继续维护和改进这个项目。不过有一些问题是，vue-danmaku这套项目开发的挺早的，项目脚手架的很多设计都比较过时了，包括弹幕的核心实现和性能问题等其实有很大提升空间，虽然有很多其他优化的想法，但是目前自己有其他优先级更高的事情要做，所以暂时搁置了。

如果你有兴趣并打算继续维护和改进这个项目话，我的建议是最好参考一些大厂的开源弹幕系统实现，比如字节的和b站的，都做的很不错，仅依赖我的项目可能会限制你的视野。

另外，这种直接复制他人的项目，并在未经原作者许可的情况下以不同的名称发布，挺不道德的。同为开发人员，希望下次在做这种事的时候，尽量提前与原作者进行沟通。

为了避免不必要的争端和麻烦，我fork了该项目的当前状态作为记录。我很欢迎你能继续改进和维护，但我希望你能在README中明确标注项目的原始来源，这不仅是对原创开发者的尊重，也是符合开源社区精神和道德标准的做法。

希望你以诚实和透明的方式参与开源社区。

**Comment by dshuais** [comment]
digua大佬，你好，很荣幸能被您看到也同样很遗憾是以这样的方式。是的您说的没错 这个仓库是借鉴了您vue-danmaku的全部思路，初衷是本着学习和提升自己为前提下载了您的项目并理解了整体逻辑和流程。后来为了使用方便和觉得有些地方可以优化 就自己写了这个仓库，可以看到 文档和整体思路都还是您的。至于没有注明出处和及时跟您联系 我对此深表歉意，本是想着在所有东西优化完后和我的博客完成之后联系您的，我深表歉意！
也很感谢您的指正和建议，因为我还只是刚入门前端的小学生，所以现阶段看了您的代码和思路让我也学到了很多，再次对您表示感谢。
您的指正 我一定会及时纠正！

**Comment by hellodigua** [comment]
没关系的，搞清楚初衷就好了，只要不是恶意的就好。

另外能麻烦你把个人主页上面的弹幕自我介绍删除吗，或者改成你自己的也可以。主页的风格被很多人借鉴过了，我倒是不介意，但是在别人的主页上面看到我的个人介绍标签觉的蛮怪的。

**Comment by dshuais** [comment]
哈哈好的，那个是刚开始用的时候还并没有自己去做的时候直接模仿和copy您的。
一定及时改正。非常感谢您的谅解！

**Comment by hellodigua** [comment]
好的，期待之后有自己的创意
