### ISSUE TITLE
宽度设置100%显示异常

### ISSUE THREAD

**Issue by JIASHIJIE530** [dshuais/danmaku-vue#15]
在父组件内     
<a-grid-item :span="{ xl: 35, lg: 44, md: 44, sm: 1, xs: 1 }" :offset="{ xl: 2, lg: 3, md: 3 }">
            <MessageBoards class="message-boards" />
</a-grid-item>
MessageBoards 组件为弹幕组件，
  <Danmaku :danmus="danmus"  class="m"></Danmaku>
想要为m设置width100%,hight100%充满容器

**Comment by JIASHIJIE530** [comment]
![Uploading 屏幕截图 2023-11-16 182813.png…]()

**Comment by dshuais** [comment]
您好 已解决了是吗？

**Comment by JIASHIJIE530** [comment]
> 您好 已解决了是吗？

不太好描述，加个好友？

**Comment by JIASHIJIE530** [comment]
> > 您好 已解决了是吗？
> 
> 不太好描述，加个好友？

**Comment by dshuais** [comment]
可以的，有需要加我q1137896420
