### ISSUE TITLE
新增功能-支持弹幕纵向滚动

### ISSUE THREAD

**Issue by jimbunny** [dshuais/danmaku-vue#16]
### 问题
是否可以支持弹幕纵向滚动
- danmaku-vue 版本: [e.g. v0.1.0]
- Vue 版本: [e.g. v2.0, v2.5, v2.6, v3.3]

**Comment by dshuais** [comment]
hello, 欢迎使用 `danmaku-vue`

我近期在忙别的项目，暂时没有新增纵向弹幕的打算，你可以尝试将舞台旋转、文字旋转等方式试试呢。
