### ISSUE TITLE
更改滚动过的数据插槽内的内容没有更改

### ISSUE THREAD

**Issue by zth19960413** [dshuais/danmaku-vue#17]
### 问题
我想要更改已经滚动过的数据的值但是更改过后，显示的值并没有更改，是因为数据绑定的问题吗

### 代码实现
<template #dm="{ danmu }">
        <div class="danmu-suspend-i">
          <span>{{ danmu.A }}</span>
          <el-button type="success" plain size="small" @click="gaibian(danmu)">改变</el-button>
        </div>
      </template>
function gaibian(item) {
  item.A = "BBBBB";
}

```

```

### 环境

- danmaku-vue 版本: [e.g. v0.1.0]
- Vue 版本: [e.g. v2.0, v2.5, v2.6, v3.3]

**Comment by dshuais** [comment]
欢迎使用 Danmaku-vue 插件。

是的，因为弹幕底层是通过动态节点创建，所以slot传递的danmu并不具备响应式，暂不支持通过直接更改danmu的方式修改数据。

不过这是个很好的理念，后续会考虑如此优化。但在目前你可以通过一些其他方式达成你的目的。

这里是我根据你的需求做的一个测试用例，仅供参考 https://github.com/dshuais/danmaku-vue/tree/test_17
